### ISSUE TITLE
Running from GUI with click does not save particle file.

### ISSUE THREAD

**Issue by Mir1001** [raeleus/Particle-Park-Pro#2]
*Ver 0.0.2*

<img width="984" alt="image" src="https://github.com/raeleus/Particle-Park-Pro/assets/623148/1e9dec65-e445-4ac5-b38f-ea6d3dd6938a">

- Clicking on the file opens the editor (it works), only *saving is not working*. Also, no error message is reported.

Running from console java -jar particleparkpro.jar is working.

**Comment by raeleus** [comment]
What operating system are you running? Thanks.

**Comment by Mir1001** [comment]
- MacBook M1 Ventura 13.4.1 
- java terminal
java -v
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

- GUI JavaLauncher.app
./java_home -v v
/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home

**Comment by raeleus** [comment]
M1 is a hard target for me test for, so I appreciate your feedback on this. I'm starting to write a wiki and these are the steps that I think may solve the issue:

![image](https://github.com/raeleus/Particle-Park-Pro/assets/12948924/a958c55e-780a-4155-9abf-9a75909c23a2)
