### ISSUE TITLE
Small glitch: Custom PPM isn't applied to preview widget when the editor is loaded

### ISSUE THREAD

**Issue by rafaskb** [raeleus/Particle-Park-Pro#4]
The value itself is properly saved and loaded, and is correct in the preview settings menu, but for some reason it's not being instantly applied to the preview widget itself when the editor is loaded. Changing the value to anything else fixes the issue.

https://github.com/raeleus/Particle-Park-Pro/assets/2331058/661adc2f-68cc-4309-ab48-030e76307d4e

**Comment by raeleus** [comment]
Thanks for pointing this out! This will be resolved in the new repo. Stay tuned!
